export const DEPARTMENTS = [
  'Sundry',
  'Sorting',
  'Assembly',
  'Cold Press',
  'Repair',
  'Hot Press',
  'Putty',
  'Sunder',
  'Spreadersizer',
  'Packing/Classifying',
  'Putty Make Up',
  'Sand Paper',
  'Paint Black',
  'Bundle',
  'Logo',
]
